Updated link script

diff --git a/link b/link
--- a/link
+++ b/link
@@ -15,7 +15,7 @@ showHelp() {
 pickHost() {
   if [ $host = "default" ]; then
     mkdir -p $PROGRAM_TARGET
-    if [ ! -d "$SCRIPT_PATH/file" ]; then
+    if [ ! -d "$SCRIPT_PATH/default" ]; then
       echo "Error: The files for this configuration are missing"
       exit 1
     fi
@@ -46,6 +46,25 @@ pickHost() {
       echo "    - The target is $STRIPPED_TARGET"
     else
       echo "Error: Failed to create symbolic links in configuration $host"
+      exit 1
+    fi
+
+    exit 0
+  fi
+  if [ $host = "sudo" ]; then
+    sudo mkdir -p $STRIPPED_TARGET
+    if [ ! -d "$SCRIPT_PATH/sudo" ]; then
+      echo "Error: The files for this configuration are missing"
+      exit 1
+    fi
+    sudo \cp -rf $SCRIPT_PATH/sudo/$PROGRAM_NAME/. $STRIPPED_TARGET
+
+    if [ $? -eq 0 ]; then
+      echo "Successfully copied files for the $PROGRAM_NAME package"
+      echo "    - The configuration is $host"
+      echo "    - The target is $PROGRAM_TARGET"
+    else
+      echo "Error: Failed to copy files in configuration $host"
       exit 1
     fi
 
